#pragma once

#define WS2812_PWM_DRIVER PWMD1
#define WS2812_PWM_CHANNEL 3
#define WS2812_PWM_COMPLEMENTARY_OUTPUT
#define WS2812_DMA_STREAM STM32_DMA1_STREAM5
#define WS2812_DMA_CHANNEL 5
#define DYNAMIC_KEYMAP_LAYER_COUNT 6

#define RGBLIGHT_DEFAULT_HUE 16
#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_TWINKLE + 2